import java.util.Vector;

public class votingService 
{
    // Amount of answer each answer submitted by students
    private int answerA;
    private int answerB;
    private int answerC;
    private int answerD;

    String type;
    Vector<String> questionAnswer;

    // Creates votinService object based on question
    public votingService(question question)
    {
        type = question.getType();
        questionAnswer = question.getAnswer();

    }

    // Takes in student object and adds the answer generated by student a list 
    public void questionSubmission(student studentAnswer)
    {
        Vector<String> answers = studentAnswer.getAnswer() ;

        for(int i = 0; i < answers.size(); i++)
        {
            
            switch(answers.get(i))
            {
                case("A"):
                {
                    answerA++;
                    break;
                }
                case("B"):
                {
                    answerB++;
                    break;
                }
                case("C"):
                {
                    answerC++;
                    break;
                }
                default:
                {
                    answerD++;
                    break;
                }
            }
            
        }
    }

    // Displays question type and answer to the question, along with submission for each answer by students
    public void displayResults()
    {
        System.out.println("Question Type: " + type);
        System.out.print("Answer(s):");
        for(int i = 0; i< questionAnswer.size(); i++)
        {
            System.out.print(" " + questionAnswer.get(i));
        }
        System.out.println("\nA: "+ answerA + 
                            "\nB: " + answerB +
                            "\nC: " + answerC +
                            "\nD: " + answerD);
    }
}
